QuestNew("Teleport Orb", "Teleport Orb");
QuestGiver(instTeleportConsole);
QuestDialogueContext(Context.intro);
QuestDialogueBegin(0);
QuestDialogue("WARNING. TELEPORT ORB MISSING. CONSOLE ERROR.");
QuestDialogueAccept(1, 2, "I wonder where that orb could be...", "What do I care about some orb?");
QuestDialogueBegin(1);
QuestDialogue('ORB REMOVED BY LIFEFORM "SQUIRREL KING".');
QuestDialogueBegin(2);
QuestDialogue("CONSOLE ERROR.");
QuestDialogueContext(Context.progress);
QuestDialogueBegin(0);
QuestDialogue("TELEPORT ORB NOT DETECTED.");
QuestDialogueContext(Context.ending);
QuestDialogueBegin(0);
QuestDialogue("TELEPORT ORB DETECTED.");
QuestDialogue("ACTIVATING TELEPORT SEQUENCE.");
QuestCondition(CheckItemInventory, ItemGetTeleportOrb());
QuestEffect(EffectTeleport, rmStart, 6, objSTEPSSquare);
